use_frameworks!

platform :ios, '9.0'

target 'CJGNavigationController_Example' do
  pod 'CJGNavigationController', :path => '../'

  target 'CJGNavigationController_Tests' do
    inherit! :search_paths

    
  end
end
